
#ID del servidor
serverId: "455476931463217174"

#Token del bot
token: "OTg5MjQwMjI1NTU5NjI1Nzc4.GYrzB5.2axfmwkYGwFnoULvUEd1qUFuux-ZfinQI1y4dU"

announce:
#Canal de anuncios en español
  es: "736542255812444203"
#Canal de anuncios en inglés
  en: "971586635399561266"

poll:
#Canal de encuestas en español
  es: "745488851904102450"
#Canal de encuestas en inglés
  en: "971586942280019998"
#Canal donde se envian las encuestas a revision
  review_channel_es: "998733623849136198"
  review_channel_en: "998733623849136198"

#Canal donde se envian las encuestas aceptadas
  accepted_channel_es: "998733855714459779"
  accepted_channel_en: "998733855714459779"
  votes_until_review: 1
lock_unlock:
#Roles que se les quita/agrega permiso de hablar
  roles:
    - "1004380482168963195"
    - "949663852902113360"

report:
#Canal donde llegan los reportes
  report_channel: "1017973286988169236"
#Canal donde llegan los reportes de bugs
  reportbug_channel: "1017973370937167872"

status:
#API de la cual se obtienen los datos del estado
  api: "https://api.mcsrvstat.us/2/nasgar.online"
  offline: "El servidor está apagado"

giveaways:
#Sorteos
  reaction: "🎉"
  embed:
    content: "🎉**SORTEO INICIADO** 🎉"
    reacciona: "¡Reacciona con 🎉 para participar!"
    ends: "Acaba {timestamp}"
    hostedby: "Iniciado por: {this.hostedBy}"
    footer: "{this.winnerCount} ganador(es)"
    color: "#FF0000"

  embedend:
    content: "🎉 **SORTEO ACABADO** 🎉"
    winners: "Ganador(es)\n"
    time: "Acabado"
    color: "#FF0000"

  messages:
    winners: "🎉 **¡Felicidades!** 🎉\nLos ganador(es) del sorteo fue(ron): {winners}\nHa(n) ganado: **{this.prize}**"
    cancelled: "¡No entraron suficientes participantes al sorteo, se canceló el sorteo!"
    reroll: "🎉 **Nuevo(s) ganador(es):** 🎉\n{winners}\nFelicidades, ha(n) ganado: **{this.prize}**\n{this.messageURL}"
    notenoughmembers: "🚫 No hubieron participantes suficientes para re-sortear."

suggestionsEs:
#Canal(es) de sugerencias en español
  channels:
    - "998734632369520640"
#Canal donde se envian las sugerencias a revision
  review_channel: "998734876054392892"
#Canal donde se envian las sugerencias aceptadas
  accepted_channel: "998734898229694504"
#Reacciones
  reactions:
    up: "✅"
    down: "❌"
#Cantidad de votos que debe tener la sugerencia antes de ser enviada a revisión
  votes_until_review: 1

suggestionsEn:
#Lo de arriba pero en inglés
  channels:
    - "998734664749568050"
  review_channel: "998734876054392892"
  accepted_channel: "998734898229694504"
  reactions:
    up: "✅"
    down: "❌"
  votes_until_review: 1


verification:
#Rol ESPAÑOL
  en_rol: "971586129751076924"
#Rol INGLÉS
  es_rol: "971586232175955969"
#Rol(es) Verificado
  verified_roles:
    - "745440633216303145"
#Botones
  button_es:
    label: "Español"
#Colores:
# 1 -> Azul
# 2 -> Gris
# 3 -> Verde
# 4 -> Rojo
    color: 2
  button_en:
    label: "English"
    color: 2
  button_esn:
    label: "Español / English"
    color: 2
  button_verify_es:
    label: "Verificar"
    color: 3
    emoji: "✅"
  button_verify_en:
    label: "Verify"
    color: 3
    emoji: "✅"

tickets_voice:
  #Rol del staff (se le daran permisos de unirse)
  staffESRolId: "991931583219118121"
  staffENRolId: "660260944882040853"
  #Categoria donde se crean los tickets de voz
  parents:
    es: "998732404061638766"
    en: "998732499976990840"
  #Limite de usuarios del canal de voz
  userlimit: 3

commands:
  say:
    es: "Haz que el bot diga lo que quieras." #Descripción del comando en español
    en: "Make the bot say something" #Descripción del comando en inglés
    rol:
      - "659579740436299786" #Rol requerido para usar el comando
  avatar:
    es: "Muestra tu avatar o el de otro usuario."
    en: "Shows your or another user 's avatar"
    rol:
      - "745440633216303145"
  addrole:
    es: "Agrega un rol a un usuario."
    en: "Adds a rol to an user"
    rol:
      - "921445728189030401"
  announce:
    es: "Envía un anuncio a ambos canales."
    en: "Sends an announce"
    rol:
      - "659579740436299786"
  info:
    es: "Muestra información del servidor."
    en: "Shows server info"
    rol:
      - "745440633216303145"
  ip:
    es: "Muestra la IP del servidor."
    en: "Shows server's ip"
    rol:
      - "745440633216303145"
  invite:
    es: "Muestra la invitación al discord."
    en: "Shows the discord invite"
    rol:
      - "745440633216303145"
  nick:
    es: "Modifica el nickname de un usuario."
    en: "Modifies the nickname of an user"
    rol:
      - "921445728189030401"
  num:
    es: "Selecciona un número al azar."
    en: "Selects a random number"
    rol:
      - "745440633216303145"
  removerole:
    es: "Remueve un rol de un usuario"
    en: "Removes a rol from an user"
    rol:
      - "659579747528867840"
  purge:
    es: "Elimina una cantidad de mensajes de un canal"
    en: "Deletes some messages on the channel"
    rol:
      - "659579747528867840"
  setdelay:
    es: "Establece el slowmode en un canal"
    en: "Set the slowmode time on a channel"
    rol:
      - "659579740436299786"
  flipcoin:
    es: "Obtiene un resultado aleatorio entre cara y cruz"
    en: "Face or cross"
    rol:
      - "745440633216303145"
  banlist:
    es: "Muestra la lista de baneos"
    en: "Shows ban list"
    rol:
      - "659579747528867840"
  lock:
    es: "Bloquea el canal a usuarios."
    en: "Lock the channel for normal users"
    rol:
      - "659579747528867840"
  unlock:
    es: "Des-Bloquea el canal a usuarios"
    en: "Unlock the channel for normal users"
    rol:
      - "659579747528867840"
  report:
    es: "Reporta a un usuario"
    en: "Report an user"
    rol:
      - "745440633216303145"
  reportbug:
    es: "Reporta un bug"
    en: "Alerts staffs about a bug"
    rol:
      - "745440633216303145"
  status:
    es: "Muestra los jugadores online en un servidor"
    en: "Shows the number of online players"
    rol:
      - "745440633216303145"
  ban:
    es: "Banea a un usuario"
    en: "Ban an user"
    rol:
      - "659579747528867840"
  unban:
    es: "Des-Banea a un usuario"
    en: "Unban an user"
    rol:
      - "659579747528867840"
  kick:
    es: "Kickea a un usuario del servidor"
    en: "Kick an user"
    rol:
      - "659579747528867840"
  mute:
    es: "Silencia a un usuario"
    en: "Mute an user"
    rol:
      - "659579747528867840"
  unmute:
    es: "Remueve el silencio de un usuario"
    en: "Unmute an user"
    rol:
      - "659579747528867840"
  giveaway start:
    es: "Inicia un sorteo"
    en: "Starts a giveaway"
    rol:
      - "659579747528867840"
  giveaway end:
    es: "Acaba un sorteo"
    en: "Forcibbly ends a giveaway"
    rol:
      - "659579747528867840"
  giveaway reroll:
    es: "Elige nuevos ganadores para un sorteo"
    en: "Randomly choose new winners"
    rol:
      - "659579747528867840"
  accept:
    es: "Acepta una sugerencia"
    en: "Accept a suggestion"
    rol:
      - "659579740436299786"
  panel:
    es: "Mensajes de setup"
    en: "Setup messages"
    rol:
      - "659579740436299786"
  voice:
    es: "Crea un ticket de voz"
    en: "Create a new voice ticket"
    rol:
      - "659579740436299786"
  close-voice:
    es: "Cierra un ticket de voz"
    en: "Delete a voice ticket"
    rol:
      - "659579740436299786"
  poll:
    es: "Crea una votacion"
    en: "Create a poll"
    rol:
      - "659579740436299786"
  rise:
    es: "Sube un ticket de nivel"
    en: "Admin rise"
    rol:
      - "659579740436299786"
  decrease:
    es: "Baja un ticket de nivel"
    en: "Admin decrease"
    rol:
      - "659579740436299786"
  acceptpoll:
    es: "Acepta una votación"
    en: "Accepts a poll"
    rol:
      - "659579740436299786"